spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    connect-timeout: 1000
    lettuce:
      pool:
        enabled: true
        max-active: 10
        max-idle: 10
        min-idle: 10
        max-wait: 1000ms
